### ISSUE TITLE
Add doc about what is kintohub

### ISSUE THREAD

**Issue by bakayolo** [kintoproj/kinto-docs#2]
**Is your feature request related to a problem? Please describe.**
Except kintohub.com users have no way to understand what is kintohub if they only look at our github org

**Describe the solution you'd like**
We should add description in the README of kinto-docs. Similar to https://github.com/argoproj/argo-workflows.

**Describe alternatives you've considered**
I thought about doing this on other repo but it would not make much sense right now since other repo have information about how to run the code. So we'll see in the future if we want to handle differently.

**Comment by bakayolo** [comment]
@nandiheath so this ticket here https://github.com/kintoproj/kinto-core/issues/21 is a duplicate of this one right?
We agree that we will create a new repo for this?

**Comment by nandiheath** [comment]
> @nandiheath so this ticket here [kintoproj/kinto-core#21](https://github.com/kintoproj/kinto-core/issues/21) is a duplicate of this one right?
> We agree that we will create a new repo for this?

we will but we should still keep that part on docs (here) too

**Comment by nandiheath** [comment]
closed by #5
