### ISSUE TITLE
Migrate kinto-examples from kintohub-examples to kintoproj

### ISSUE THREAD

**Issue by bakayolo** [kintoproj/kinto-docs#9]
All our examples are still stored in https://github.com/kintohub-examples/.
We should migrate them into a single monorepo under the new kintoproj organization.

 /!\ make sure the references in kinto-docs are all being updated.

**Comment by codingben** [comment]
kinto-docs PR: https://github.com/kintoproj/kinto-docs/pull/10

**Comment by codingben** [comment]
Done! https://github.com/kintoproj/kinto-examples

**Comment by codingben** [comment]
We need to delete duplicated folders later:

1. gatsby (we also have gatsby-site)
2. nodejs (we also have nodejs-api)
3. nextjs (we also have nextjs-web-app)
4. preact (we also have react)
5. react (we also have preact and todo-react)
6. ruby (we also have ruby-api)

**Comment by codingben** [comment]
> We need to delete duplicated folders later:
> 
> 1. gatsby (we also have gatsby-site)
> 2. nodejs (we also have nodejs-api)
> 3. nextjs (we also have nextjs-web-app)
> 4. preact (we also have react)
> 5. react (we also have preact and todo-react)
> 6. ruby (we also have ruby-api)

@bappr before deleting them we have to make sure we don't have reference to one of the folders.
